version: '3.9'

services:
  osc-webhook:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/code/osc-webhook
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-1}
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-*info*,*warn*,*error*}
      - domain
      - token
